[package]
name = "prettyasserts"
description = "A preprocessor that makes C asserts easier to debug"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3.26"
anyhow = "1.0.79"
regex = "1.10.3"
either = "1.9.0"
