// Generated by __PRETTY_ASSERT_COMMAND:
//
// __PRETTY_ASSERT_ARGS
//

#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
// give source a chance to define feature macros
#undef _FEATURES_H

// print macros
__attribute__((unused))
static void __pretty_assert_bool(
        const void *v, size_t size) {
    (void)size;
    printf("%s", *(const bool*)v ? "true" : "false");
}

__attribute__((unused))
static void __pretty_assert_int(
        const void *v, size_t size) {
    (void)size;
    printf("%"PRIiMAX, *(const intmax_t*)v);
}

__attribute__((unused))
static void __pretty_assert_mem(
        const void *v, size_t size) {
    const uint8_t *v_ = v;
    printf("\"");
    for (size_t i = 0; i < size && i < __PRETTY_ASSERT_LIMIT; i++) {
        if (v_[i] >= ' ' && v_[i] <= '~') {
            printf("%c", v_[i]);
        } else {
            printf("\\x%02x", v_[i]);
        }
    }
    if (size > __PRETTY_ASSERT_LIMIT) {
        printf("...");
    }
    printf("\"");
}

__attribute__((unused))
static void __pretty_assert_str(
        const void *v, size_t size) {
    __pretty_assert_mem(v, size);
}

__attribute__((unused))
static void __pretty_assert_print(
        const char *file, int line,
        void (*type_print_cb)(const void*, size_t),
        const char *cmp,
        const void *lh, size_t lsize,
        const void *rh, size_t rsize) {
    printf("%s:%d:assert: assert failed with ", file, line);
    type_print_cb(lh, lsize);
    printf(", expected %s ", cmp);
    type_print_cb(rh, rsize);
    printf("\n");
    fflush(NULL);
}

__attribute__((unused))
static void __pretty_assert_print_unreachable(
        const char *file, int line) {
    printf("%s:%d:unreachable: "
            "unreachable statement reached\n", file, line);
    fflush(NULL);
}


// assert macros
#define __PRETTY_ASSERT_BOOL_CMP(cmp, lh, op, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh op _rh)) { \
        __pretty_assert_print( \
                __FILE__, __LINE__, \
                __pretty_assert_bool, #cmp, \
                &_lh, 0, \
                &_rh, 0); \
        __builtin_trap(); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_EQ(lh, rh) __PRETTY_ASSERT_BOOL_CMP(eq, lh, ==, rh)
#define __PRETTY_ASSERT_BOOL_NE(lh, rh) __PRETTY_ASSERT_BOOL_CMP(ne, lh, !=, rh)
#define __PRETTY_ASSERT_BOOL_LT(lh, rh) __PRETTY_ASSERT_BOOL_CMP(lt, lh, <,  rh)
#define __PRETTY_ASSERT_BOOL_GT(lh, rh) __PRETTY_ASSERT_BOOL_CMP(gt, lh, >,  rh)
#define __PRETTY_ASSERT_BOOL_LE(lh, rh) __PRETTY_ASSERT_BOOL_CMP(le, lh, <=, rh)
#define __PRETTY_ASSERT_BOOL_GE(lh, rh) __PRETTY_ASSERT_BOOL_CMP(ge, lh, >=, rh)

#define __PRETTY_ASSERT_INT_CMP(cmp, lh, op, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh op _rh)) { \
        __pretty_assert_print( \
                __FILE__, __LINE__, \
                __pretty_assert_int, #cmp, \
                &(intmax_t){(intmax_t)_lh}, 0, \
                &(intmax_t){(intmax_t)_rh}, 0); \
        __builtin_trap(); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_EQ(lh, rh) __PRETTY_ASSERT_INT_CMP(eq, lh, ==, rh)
#define __PRETTY_ASSERT_INT_NE(lh, rh) __PRETTY_ASSERT_INT_CMP(ne, lh, !=, rh)
#define __PRETTY_ASSERT_INT_LT(lh, rh) __PRETTY_ASSERT_INT_CMP(lt, lh, <,  rh)
#define __PRETTY_ASSERT_INT_GT(lh, rh) __PRETTY_ASSERT_INT_CMP(gt, lh, >,  rh)
#define __PRETTY_ASSERT_INT_LE(lh, rh) __PRETTY_ASSERT_INT_CMP(le, lh, <=, rh)
#define __PRETTY_ASSERT_INT_GE(lh, rh) __PRETTY_ASSERT_INT_CMP(ge, lh, >=, rh)

#define __PRETTY_ASSERT_MEM_CMP(cmp, lh, op, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) op 0)) { \
        __pretty_assert_print( \
                __FILE__, __LINE__, \
                __pretty_assert_mem, #cmp, \
                _lh, size, \
                _rh, size); \
        __builtin_trap(); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_EQ(lh, rh, size) __PRETTY_ASSERT_MEM_CMP(eq, lh, ==, rh, size)
#define __PRETTY_ASSERT_MEM_NE(lh, rh, size) __PRETTY_ASSERT_MEM_CMP(ne, lh, !=, rh, size)
#define __PRETTY_ASSERT_MEM_LT(lh, rh, size) __PRETTY_ASSERT_MEM_CMP(lt, lh, <,  rh, size)
#define __PRETTY_ASSERT_MEM_GT(lh, rh, size) __PRETTY_ASSERT_MEM_CMP(gt, lh, >,  rh, size)
#define __PRETTY_ASSERT_MEM_LE(lh, rh, size) __PRETTY_ASSERT_MEM_CMP(le, lh, <=, rh, size)
#define __PRETTY_ASSERT_MEM_GE(lh, rh, size) __PRETTY_ASSERT_MEM_CMP(ge, lh, >=, rh, size)

#define __PRETTY_ASSERT_STR_CMP(cmp, lh, op, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) op 0)) { \
        __pretty_assert_print( \
                __FILE__, __LINE__, \
                __pretty_assert_str, #cmp, \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
        __builtin_trap(); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_EQ(lh, rh) __PRETTY_ASSERT_STR_CMP(eq, lh, ==, rh)
#define __PRETTY_ASSERT_STR_NE(lh, rh) __PRETTY_ASSERT_STR_CMP(ne, lh, !=, rh)
#define __PRETTY_ASSERT_STR_LT(lh, rh) __PRETTY_ASSERT_STR_CMP(lt, lh, <,  rh)
#define __PRETTY_ASSERT_STR_GT(lh, rh) __PRETTY_ASSERT_STR_CMP(gt, lh, >,  rh)
#define __PRETTY_ASSERT_STR_LE(lh, rh) __PRETTY_ASSERT_STR_CMP(le, lh, <=, rh)
#define __PRETTY_ASSERT_STR_GE(lh, rh) __PRETTY_ASSERT_STR_CMP(ge, lh, >=, rh)

#define __PRETTY_ASSERT_UNREACHABLE() do { \
    __pretty_assert_print_unreachable( \
            __FILE__, __LINE__); \
    __builtin_trap(); \
} while (0)


